remote_read:
  - url: "http://localhost:9201/read"
remote_write:
  - url: 'http://localhost:9201/write'

scrape_configs:
  - job_name: 'spring'
    metrics_path: '/admin/actuator/prometheus'
    scheme: http
    static_configs:
      - targets: ['localhost:8080']
    basic_auth:
      username: superadmin
      password: "super@dmin"
